# Generated by Django 5.1.15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='金額')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出',
                'ordering': ['-date', '-created_at', '-id'],
            },
        ),
    ]
