# Generated by Django 5.1.15 on 2026-04-11 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expenseentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', '家賃'), ('food', '食費'), ('utilities', '光熱費'), ('social', '交際費'), ('communication', '通信費'), ('daily_goods', '日用品'), ('transport', '交通費'), ('medical', '医療・健康'), ('insurance', '保険'), ('education', '教育・習い事'), ('other', 'その他')], max_length=32, verbose_name='カテゴリ')),
                ('monthly_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='月間予算（円）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '支出予算',
                'verbose_name_plural': '支出予算',
                'ordering': ['category'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='accounts_expensebudget_user_category_uniq')],
            },
        ),
    ]
