# Generated by Django 5.1.15 on 2026-04-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_expensebudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('rent', '家賃'), ('food', '食費'), ('utilities', '光熱費'), ('social', '交際費'), ('communication', '通信費'), ('daily_goods', '日用品'), ('transport', '交通費'), ('medical', '医療・健康'), ('insurance', '保険'), ('education', '教育・習い事'), ('other', 'その他')], default='other', max_length=32, verbose_name='カテゴリ'),
        ),
    ]
