# Generated by Django 5.1.15 on 2026-04-20 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_expenseentry_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('events', models.TextField(blank=True, verbose_name='出来事')),
                ('tomorrow_goals', models.TextField(blank=True, verbose_name='明日の目標')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日記',
                'verbose_name_plural': '日記',
                'ordering': ['-date', '-created_at', '-id'],
            },
        ),
    ]
